QT += testlib network
QT -= gui

CONFIG += qt console warn_on depend_includepath testcase
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += \
    ../src/telegram/animation.cpp \
    ../src/telegram/audio.cpp \
    ../src/telegram/callbackgame.cpp \
    ../src/telegram/callbackquery.cpp \
    ../src/telegram/chat.cpp \
    ../src/telegram/chatinvitelink.cpp \
    ../src/telegram/chatjoinrequest.cpp \
    ../src/telegram/chatlocation.cpp \
    ../src/telegram/chatmember.cpp \
    ../src/telegram/chatmemberadministrator.cpp \
    ../src/telegram/chatmemberbanned.cpp \
    ../src/telegram/chatmemberleft.cpp \
    ../src/telegram/chatmembermember.cpp \
    ../src/telegram/chatmemberowner.cpp \
    ../src/telegram/chatmemberrestricted.cpp \
    ../src/telegram/chatmemberupdated.cpp \
    ../src/telegram/chatpermissions.cpp \
    ../src/telegram/chatphoto.cpp \
    ../src/telegram/choseninlineresult.cpp \
    ../src/telegram/common.cpp \
    ../src/telegram/contact.cpp \
    ../src/telegram/dice.cpp \
    ../src/telegram/document.cpp \
    ../src/telegram/encryptedcredentials.cpp \
    ../src/telegram/encryptedpassportelement.cpp \
    ../src/telegram/game.cpp \
    ../src/telegram/inlinekeyboardbutton.cpp \
    ../src/telegram/inlinekeyboardmarkup.cpp \
    ../src/telegram/inlinequery.cpp \
    ../src/telegram/invoice.cpp \
    ../src/telegram/location.cpp \
    ../src/telegram/loginurl.cpp \
    ../src/telegram/maskposition.cpp \
    ../src/telegram/message.cpp \
    ../src/telegram/messageautodeletetimerchanged.cpp \
    ../src/telegram/messageentity.cpp \
    ../src/telegram/orderinfo.cpp \
    ../src/telegram/passportdata.cpp \
    ../src/telegram/passportfile.cpp \
    ../src/telegram/photosize.cpp \
    ../src/telegram/poll.cpp \
    ../src/telegram/pollanswer.cpp \
    ../src/telegram/polloption.cpp \
    ../src/telegram/precheckoutquery.cpp \
    ../src/telegram/proximityalerttriggered.cpp \
    ../src/telegram/shippingaddress.cpp \
    ../src/telegram/shippingquery.cpp \
    ../src/telegram/sticker.cpp \
    ../src/telegram/successfulpayment.cpp \
    ../src/telegram/update.cpp \
    ../src/telegram/user.cpp \
    ../src/telegram/venue.cpp \
    ../src/telegram/video.cpp \
    ../src/telegram/videonote.cpp \
    ../src/telegram/voice.cpp \
    ../src/telegram/voicechatended.cpp \
    ../src/telegram/voicechatparticipantsinvited.cpp \
    ../src/telegram/voicechatscheduled.cpp \
    ../src/telegram/voicechatstarted.cpp \
    main.cpp \
    telegram/tst_telegramapi.cpp \

HEADERS += \
    ../src/telegram/animation.h \
    ../src/telegram/audio.h \
    ../src/telegram/callbackgame.h \
    ../src/telegram/callbackquery.h \
    ../src/telegram/chat.h \
    ../src/telegram/chatinvitelink.h \
    ../src/telegram/chatjoinrequest.h \
    ../src/telegram/chatlocation.h \
    ../src/telegram/chatmember.h \
    ../src/telegram/chatmemberadministrator.h \
    ../src/telegram/chatmemberbanned.h \
    ../src/telegram/chatmemberleft.h \
    ../src/telegram/chatmembermember.h \
    ../src/telegram/chatmemberowner.h \
    ../src/telegram/chatmemberrestricted.h \
    ../src/telegram/chatmemberupdated.h \
    ../src/telegram/chatpermissions.h \
    ../src/telegram/chatphoto.h \
    ../src/telegram/choseninlineresult.h \
    ../src/telegram/common.h \
    ../src/telegram/contact.h \
    ../src/telegram/dice.h \
    ../src/telegram/document.h \
    ../src/telegram/encryptedcredentials.h \
    ../src/telegram/encryptedpassportelement.h \
    ../src/telegram/game.h \
    ../src/telegram/inlinekeyboardbutton.h \
    ../src/telegram/inlinekeyboardmarkup.h \
    ../src/telegram/inlinequery.h \
    ../src/telegram/invoice.h \
    ../src/telegram/location.h \
    ../src/telegram/loginurl.h \
    ../src/telegram/maskposition.h \
    ../src/telegram/message.h \
    ../src/telegram/messageautodeletetimerchanged.h \
    ../src/telegram/messageentity.h \
    ../src/telegram/orderinfo.h \
    ../src/telegram/passportdata.h \
    ../src/telegram/passportfile.h \
    ../src/telegram/photosize.h \
    ../src/telegram/poll.h \
    ../src/telegram/pollanswer.h \
    ../src/telegram/polloption.h \
    ../src/telegram/precheckoutquery.h \
    ../src/telegram/proximityalerttriggered.h \
    ../src/telegram/shippingaddress.h \
    ../src/telegram/shippingquery.h \
    ../src/telegram/sticker.h \
    ../src/telegram/successfulpayment.h \
    ../src/telegram/update.h \
    ../src/telegram/user.h \
    ../src/telegram/venue.h \
    ../src/telegram/video.h \
    ../src/telegram/videonote.h \
    ../src/telegram/voice.h \
    ../src/telegram/voicechatended.h \
    ../src/telegram/voicechatparticipantsinvited.h \
    ../src/telegram/voicechatscheduled.h \
    ../src/telegram/voicechatstarted.h \
    telegram/tst_telegramapi.h \
