QT += testlib network
QT -= gui

CONFIG += qt console warn_on depend_includepath testcase
CONFIG -= app_bundle

TEMPLATE = app

SOURCES += \
    ../src/telegram/api.cpp \
    ../src/telegram/types/animation.cpp \
    ../src/telegram/types/audio.cpp \
    ../src/telegram/types/callbackgame.cpp \
    ../src/telegram/types/callbackquery.cpp \
    ../src/telegram/types/chat.cpp \
    ../src/telegram/types/chatinvitelink.cpp \
    ../src/telegram/types/chatjoinrequest.cpp \
    ../src/telegram/types/chatlocation.cpp \
    ../src/telegram/types/chatmember.cpp \
    ../src/telegram/types/chatmemberadministrator.cpp \
    ../src/telegram/types/chatmemberbanned.cpp \
    ../src/telegram/types/chatmemberleft.cpp \
    ../src/telegram/types/chatmembermember.cpp \
    ../src/telegram/types/chatmemberowner.cpp \
    ../src/telegram/types/chatmemberrestricted.cpp \
    ../src/telegram/types/chatmemberupdated.cpp \
    ../src/telegram/types/chatpermissions.cpp \
    ../src/telegram/types/chatphoto.cpp \
    ../src/telegram/types/choseninlineresult.cpp \
    ../src/telegram/types/common.cpp \
    ../src/telegram/types/contact.cpp \
    ../src/telegram/types/dice.cpp \
    ../src/telegram/types/document.cpp \
    ../src/telegram/types/encryptedcredentials.cpp \
    ../src/telegram/types/encryptedpassportelement.cpp \
    ../src/telegram/types/forcereply.cpp \
    ../src/telegram/types/game.cpp \
    ../src/telegram/types/inlinekeyboardbutton.cpp \
    ../src/telegram/types/inlinekeyboardmarkup.cpp \
    ../src/telegram/types/inlinequery.cpp \
    ../src/telegram/types/invoice.cpp \
    ../src/telegram/types/keyboardbutton.cpp \
    ../src/telegram/types/keyboardbuttonpolltype.cpp \
    ../src/telegram/types/location.cpp \
    ../src/telegram/types/loginurl.cpp \
    ../src/telegram/types/maskposition.cpp \
    ../src/telegram/types/message.cpp \
    ../src/telegram/types/messageautodeletetimerchanged.cpp \
    ../src/telegram/types/messageentity.cpp \
    ../src/telegram/types/orderinfo.cpp \
    ../src/telegram/types/passportdata.cpp \
    ../src/telegram/types/passportfile.cpp \
    ../src/telegram/types/photosize.cpp \
    ../src/telegram/types/poll.cpp \
    ../src/telegram/types/pollanswer.cpp \
    ../src/telegram/types/polloption.cpp \
    ../src/telegram/types/precheckoutquery.cpp \
    ../src/telegram/types/proximityalerttriggered.cpp \
    ../src/telegram/types/replykeyboardmarkup.cpp \
    ../src/telegram/types/replykeyboardremove.cpp \
    ../src/telegram/types/shippingaddress.cpp \
    ../src/telegram/types/shippingquery.cpp \
    ../src/telegram/types/sticker.cpp \
    ../src/telegram/types/successfulpayment.cpp \
    ../src/telegram/types/update.cpp \
    ../src/telegram/types/user.cpp \
    ../src/telegram/types/venue.cpp \
    ../src/telegram/types/video.cpp \
    ../src/telegram/types/videonote.cpp \
    ../src/telegram/types/voice.cpp \
    ../src/telegram/types/voicechatended.cpp \
    ../src/telegram/types/voicechatparticipantsinvited.cpp \
    ../src/telegram/types/voicechatscheduled.cpp \
    ../src/telegram/types/voicechatstarted.cpp \
    main.cpp \
    telegram/tst_telegrammethods.cpp \
    telegram/tst_telegramtypes.cpp

HEADERS += \
    ../src/telegram/api.h \
    ../src/telegram/types/animation.h \
    ../src/telegram/types/audio.h \
    ../src/telegram/types/callbackgame.h \
    ../src/telegram/types/callbackquery.h \
    ../src/telegram/types/chat.h \
    ../src/telegram/types/chatinvitelink.h \
    ../src/telegram/types/chatjoinrequest.h \
    ../src/telegram/types/chatlocation.h \
    ../src/telegram/types/chatmember.h \
    ../src/telegram/types/chatmemberadministrator.h \
    ../src/telegram/types/chatmemberbanned.h \
    ../src/telegram/types/chatmemberleft.h \
    ../src/telegram/types/chatmembermember.h \
    ../src/telegram/types/chatmemberowner.h \
    ../src/telegram/types/chatmemberrestricted.h \
    ../src/telegram/types/chatmemberupdated.h \
    ../src/telegram/types/chatpermissions.h \
    ../src/telegram/types/chatphoto.h \
    ../src/telegram/types/choseninlineresult.h \
    ../src/telegram/types/common.h \
    ../src/telegram/types/contact.h \
    ../src/telegram/types/dice.h \
    ../src/telegram/types/document.h \
    ../src/telegram/types/encryptedcredentials.h \
    ../src/telegram/types/encryptedpassportelement.h \
    ../src/telegram/types/forcereply.h \
    ../src/telegram/types/game.h \
    ../src/telegram/types/inlinekeyboardbutton.h \
    ../src/telegram/types/inlinekeyboardmarkup.h \
    ../src/telegram/types/inlinequery.h \
    ../src/telegram/types/invoice.h \
    ../src/telegram/types/keyboardbutton.h \
    ../src/telegram/types/keyboardbuttonpolltype.h \
    ../src/telegram/types/location.h \
    ../src/telegram/types/loginurl.h \
    ../src/telegram/types/maskposition.h \
    ../src/telegram/types/message.h \
    ../src/telegram/types/messageautodeletetimerchanged.h \
    ../src/telegram/types/messageentity.h \
    ../src/telegram/types/orderinfo.h \
    ../src/telegram/types/passportdata.h \
    ../src/telegram/types/passportfile.h \
    ../src/telegram/types/photosize.h \
    ../src/telegram/types/poll.h \
    ../src/telegram/types/pollanswer.h \
    ../src/telegram/types/polloption.h \
    ../src/telegram/types/precheckoutquery.h \
    ../src/telegram/types/proximityalerttriggered.h \
    ../src/telegram/types/replykeyboardmarkup.h \
    ../src/telegram/types/replykeyboardremove.h \
    ../src/telegram/types/shippingaddress.h \
    ../src/telegram/types/shippingquery.h \
    ../src/telegram/types/sticker.h \
    ../src/telegram/types/successfulpayment.h \
    ../src/telegram/types/update.h \
    ../src/telegram/types/user.h \
    ../src/telegram/types/venue.h \
    ../src/telegram/types/video.h \
    ../src/telegram/types/videonote.h \
    ../src/telegram/types/voice.h \
    ../src/telegram/types/voicechatended.h \
    ../src/telegram/types/voicechatparticipantsinvited.h \
    ../src/telegram/types/voicechatscheduled.h \
    ../src/telegram/types/voicechatstarted.h \
    telegram/tst_telegrammethods.h \
    telegram/tst_telegramtypes.h
